### ISSUE TITLE
Not all current series are shown

### ISSUE THREAD

**Issue by jeluchu** [ChrisMichaelPerezSantiago/ryuanime#162]
Ohayo developers!

I have been checking the methods and calls of certain anime of the fall season and the episodes of all the series are not shown, one of the examples is "Kono Oto Tomare 2nd Season"

I searched anime with your methods, but the answer is empty and there are no episodes of some current series

I have been doing the tests from Windows in Google Chrome, in addition to testing with Postman, but it has not given any results

I hope you can review it, thank you very much in advance for your work

Regards

**Comment by chrismichaelps** [comment]
_Hello @Jeluchu ,_

First of all I apologize for not knowing that you had sent me a message.

_Yes you are correct.
There are some series that are not showing as they should, and this is due to a problem that I have to solve in my API._

_This error mostly occurs in the anime that were recently added from the jkanime page._

_As for the anime that you mentioned to me, when I do a search, It personally show the data, both on the ryuanime page and in the API._

_I made an API migration that I had implemented that is in the same [ryuanime repository](https://github.com/ChrisMichaelPerezSantiago/ryuanime/tree/master/src/api)_

For the [jkanime repository](https://github.com/ChrisMichaelPerezSantiago/jkanime)

_In the jkanime repository I will be working to make the necessary changes._

**Comment by chrismichaelps** [comment]
_Recently I implemented a custom api from the animeflv page, which I can say is very complete._

_In case you want to try and see the documentation you can access the_ [animeflv doc](https://github.com/ChrisMichaelPerezSantiago/animeflv)

**Comment by jeluchu** [comment]
@ChrisMichaelPerezSantiago Nothing happens, I wrote the message yesterday therefore you have not taken too long to respond.

I just checked again the anime I said and now if I get it, I was testing it this Saturday and both that and others of this season were not showing me.

Thank you very much for the APIs and for your response

Anything else would tell you again

Regards!
