### ISSUE TITLE
Calendar service does not work

### ISSUE THREAD

**Issue by jeluchu** [ChrisMichaelPerezSantiago/ryuanime#172]
Good afternoon, I have verified that this service fails:
https://ryuanime-api.chrismichael.now.sh/api/v1/calender

It takes several days without showing the animes that come out by day of the week

I have been doing the tests from Windows in Google Chrome, in addition to testing with Postman, but it has not given any results

I hope you can review it, thank you very much in advance for your work

Regards

**Comment by MrZ3T4** [comment]
Right, the calendar has stopped working for a long time, I hardly noticed :D

**Comment by chrismichaelps** [comment]
_Hello @Jeluchu ,_

_Sorry for the delay._
_I have migrated the ryuanime api to the [jkanime](https://github.com/ChrisMichaelPerezSantiago/jkanime) repositiory for a long time, so I will be giving more support to the jkanime api._

_As for the calendar, I have removed it from the api for now because I need to find a way to structure the JSON format in a simple way. In the way ryuanime api had presented it, it was not the most suitable for the client side.That is why in the next few days I will be working on that part, so that you (the developer users) can use it._

_***I greatly appreciate your interest in using the API.***
***So, don't hesitate to ask me anything about the project.***_

**Comment by chrismichaelps** [comment]
_Hello @Jeluchu ,_

_I just included the schedule method to api, and other minimal changes._
_I should mention that [jkanime](https://github.com/ChrisMichaelPerezSantiago/jkanime) api only works for now using the jkanime package from npm._

_Apologies for the inconvenience._
