### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by MoptopX** [ChrisMichaelPerezSantiago/ryuanime#48]
Can you possibly make a separate branch scraping from an english site?

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @MoptopX,

Yes, it would be possible to do it. But I need a reference from some popular anime page in English.

But that content cannot be included in Ryuanime application, because it is a version for those who speak Spanish.

**Comment by MoptopX** [comment]
Yes I understand that all the content is being scraped from a site meant for Spanish subbed anime, so what my question was is can you possibly scrape from an english website like https://animedaisuki.moe, or https://www2.9anime.nl/ or https://www4.gogoanime.io/

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @MoptopX,

Thanks for the references.👍
I will try my best when I have more time.

**Comment by MoptopX** [comment]
Alright, https://animedaisuki.moe is missing some anime so I wouldn't recommend it

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @MoptopX ,

I was analyzing the possibility of scraping the https://www2.9anime.nl page, unfortunately it is impossible to do a scraping at least to take the videos.

They are using BLOB to hide the video src.

Example:

`blob: https: //prettyfast.to/186e0e7a-2ce0-42c1-8a38-f50d33a10b25`

**What is blob url? Because it is used?**

BLOB is just a sequence of bytes. The browser recognizes it as byte transmission. It is used to obtain the transmission of bytes from the source.

A Blob object represents an object similar to a raw and immutable data file. Blobs represent data that is not necessarily in a native JavaScript format.


As for the page https://www7.gogoanime.io/, it is somewhat complicated because they do not have the mp4 src visible.

**Comment by MoptopX** [comment]
Try https://anime1.com

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @MoptopX

I recommend you if you are interested in creating an API, you can use [this custom API](https://github.com/ChrisMichaelPerezSantiago/jkanime) as an example that I created to use it in my Ryuanime project.

Scraping a page is not that difficult, but it takes time.

There are two known libraries for scraping pages:
- `cheerio`
- `puppeteer`

_Cheerio is more used and easy to learn to use._
