### ISSUE TITLE
Should it be Genres instead of Genders?

### ISSUE THREAD

**Issue by kinow** [ChrisMichaelPerezSantiago/ryuanime#56]
**Describe the bug**

I am not a native speaker, but I think where it says Genders on the left sidebar, it should actually be Genres? Maybe I think...

**To Reproduce**
1. Go to the landing page
2. Check the left menu

**Expected behavior**

A link to the genres, as in Mangadex.

Thanks!

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @kinow 

You are right!
It should be genre and not gender

As for the expected Behavior, on the right side of the bar there is a dropdown with a list of genres.


I must mention that the UI of the application that is now is something temporary, I can change dramatically. So soon I will be structuring the UI better.

Any idea will be more than received

**Comment by kinow** [comment]
I was looking for vuejs apps to contribute to, so keen to help with easy tasks. Thanks!

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @kinow ,

Sorry ... I thought you were asking me to fix it. 
Once I have another issue available you can contribute.
