### ISSUE TITLE
Ryuanime not working

### ISSUE THREAD

**Issue by adamwoo2444** [ChrisMichaelPerezSantiago/ryuanime#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kinow** [comment]
It seems to be working fine for me, at least the few pages I tried? Do you have a step by step to reproduce what's broken?

**Comment by adamwoo2444** [comment]
I am saying about web. Its not playing any video.
I trid "Business Fish" but its now playing. Its been 25 mins.

**Comment by kinow** [comment]
Ah, you are correct. Successfully reproduced it here. Got some errors locally running the latest version from `master` too. Will probably need @ChrisMichaelPerezSantiago to have a look.

**Comment by adamwoo2444** [comment]
are you guys using webtorrent ?

**Comment by ChrisMichaelPerezSantiago** [comment]
@ adamwoo2444,

There are certain anime that have 25 chapters assigned. This value is assigned temporarily because of the page that I scraped the information of the chapters does not exist. Eventually Those chapters that were assigned 25 chapters not necessarily have that amount. You can see that situation in the Latest section.

For example, taking the business-fish anime as an example. Currently only one chapter has been transmitted, but the list says you have 25 chapters. There aren't really 25 chapters. That is why the other chapters are not going to be seen. As I mentioned, the explanation of why the temporary value 25 is in the first paragraph.

In the other sections the series are assigned the chapters that have been reproduced to this day.

The information on the total chapters of each anime does not depend on me being added. I only scraped a page and then I implemented an API.

**Comment by adamwoo2444** [comment]
OKAY, Thanks.
